version: "3.8"

services:
  backend:
    image: myorg/gym-api:dev
    container_name: gym-api-dev
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    environment:
      - APP_PORT=8000
      - MONGO_URI=mongodb://mongo:27017/
    ports:
      - "8000:8000"
    volumes:
      - ..:/usr/src/app
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: gym-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: